### ISSUE TITLE
some confusion on docker-index-nginx configuration in "default"

### ISSUE THREAD

**Issue by afengisme** [ekristen/docker-index-nginx#2]
Good day,

the proxy configurations as below,  I note that this configuration:  "location /"
###### 

server {
  listen *:443;
  server_name registry;
  ssl on;
  ssl_certificate /etc/nginx/ssl/certificate.crt;
  ssl_certificate_key /etc/nginx/ssl/private.key;

  client_max_body_size 0;
  proxy_set_header  Host           $http_host;   # required for docker client's sake
  proxy_set_header  X-Real-IP      $remote_addr; # pass on real client's IP

  location / {
    proxy_pass  http://registry;
  }
}

server {
  listen *:443;
  server_name index;

  ssl on;
  ssl_certificate /etc/nginx/ssl/certificate.crt;
  ssl_certificate_key /etc/nginx/ssl/private.key;

  client_max_body_size 0;
  proxy_set_header  Host           $http_host;   # required for docker client's sake
  proxy_set_header  X-Real-IP      $remote_addr; # pass on real client's IP

  location / {
    proxy_pass  http://index;
  }
}
###### 

does it mean when the access url is https://xxx.xxx.xxx/  will always proxy to http://registy priorly. 

because both server registry and index are all the same proxy-url "location /" , and server registry is at the prior position in the config file.

after fig up the containers, I tried to "docker login https://xxxx.xxx.xxx" , it was failed:
Username: admin
Password:
Email: xxx@xxx.com
FATA[0015] Error response from daemon:

Then I tried to run "docker logs <registry_container_id> " to check the logs on registry container, I found this log:
###### 

10.0.0.41 - - [22/Apr/2015:02:15:12 +0000] "POST /v1/users/ HTTP/1.0" 404 233 "-" "Go 1.1 package http"
###### 

10.0.0.41 is the nginx container IP,  this type of log ("..... POST /v1/users/ .....")  means it POST the requst to registry container,  right ?  
should not  nginx proxy send the request to index container ?  docker-index container is the right one to deal with this type of request.

Does the nginx proxy configuring "location /"  resulted that ? 

anyont encountered this issue ?

thanks a lot.

**Comment by afengisme** [comment]
I rebuilt the docker-index-nginx images with modify the nginx default file like this :

server {
  listen *:443;
  server_name INDEX_HOSTNAME;

  ssl on;
  ssl_certificate /etc/nginx/ssl/certificate.crt;
  ssl_certificate_key /etc/nginx/ssl/private.key;

  client_max_body_size 0;
  proxy_set_header  Host           $http_host;   # required for docker client's sake
  proxy_set_header  X-Real-IP      $remote_addr; # pass on real client's IP

  location /v1/ {
    proxy_pass  http://index/v1/;
  }
}

server {
  listen *:443;
  server_name REGISTRY_HOSTNAME;
  ssl on;
  ssl_certificate /etc/nginx/ssl/certificate.crt;
  ssl_certificate_key /etc/nginx/ssl/private.key;

  client_max_body_size 0;
  proxy_set_header  Host           $http_host;   # required for docker client's sake
  proxy_set_header  X-Real-IP      $remote_addr; # pass on real client's IP

  location / {
    proxy_pass  http://registry;
  }
}

then it works.

> docker login https://xxxx.xxxx.com
> Username: admin
> Password:
> Email: xxxx.xxx@xxx.com
> Login Succeeded

**Comment by afengisme** [comment]
I tried to update the nginx default file in docker-index-nginx image like this (add "v1" at the end of index url , and let index proxy configurtion at the prior position in the config file) :

server {
  listen *:443;
  server_name INDEX_HOSTNAME;

  ssl on;
  ssl_certificate /etc/nginx/ssl/certificate.crt;
  ssl_certificate_key /etc/nginx/ssl/private.key;

  client_max_body_size 0;
  proxy_set_header  Host           $http_host;   # required for docker client's sake
  proxy_set_header  X-Real-IP      $remote_addr; # pass on real client's IP

  location /v1/ {
    proxy_pass  http://index/v1/;
  }
}

server {
  listen *:443;
  server_name REGISTRY_HOSTNAME;
  ssl on;
  ssl_certificate /etc/nginx/ssl/certificate.crt;
  ssl_certificate_key /etc/nginx/ssl/private.key;

  client_max_body_size 0;
  proxy_set_header  Host           $http_host;   # required for docker client's sake
  proxy_set_header  X-Real-IP      $remote_addr; # pass on real client's IP

  location / {
    proxy_pass  http://registry;
  }
}

**Comment by ekristen** [comment]
You don't need to make any modifications to it, it passes the appropriate traffic based on hostname. 

This container was designed for use with the `fig.yml` for development and testing only, not for production.

It requires you have 1 hostname for the index and 1 hostname for the registry. For example `index.private.io` and `registry.private.io`

**Comment by afengisme** [comment]
thanks Erik

Got it,  I will deploy the docker-registry and docker-index on different physical machines for production environment.
